export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const TOGGLE = 'TOGGLE';
export const SEARCH = 'SEARCH';

export const REPORTS_ERROR = 'REPORTS_ERROR';
export const REPORTS_SUCCESS = 'REPORTS_SUCCESS';
export const REPORTS_REQUEST = 'REPORTS_REQUEST';

export const REINSTATE_REQUEST = 'REINSTATE_REQUEST';
export const REINSTATE_SUCCESS = 'REINSTATE_SUCCESS';
export const REINSTATE_ERROR = 'REINSTATE_ERROR';

export const SUSPEND_REQUEST = 'SUSPEND_REQUEST';
export const SUSPEND_SUCCESS = 'SUSPEND_SUCCESS';
export const SUSPEND_ERROR = 'SUSPEND_ERROR';

export const BOOKINGS_ERROR = 'BOOKINGS_ERROR';
export const BOOKINGS_SUCCESS = 'BOOKINGS_SUCCESS';
export const BOOKINGS_REQUEST = 'BOOKINGS_REQUEST';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
