export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const QUESTION_ERROR = 'QUESTION_ERROR';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_ERROR = 'UPLOAD_ERROR';

export const Nav = 'Nav';

export const COMPLETED_REQUEST = 'COMPLETED_REQUEST';
export const COMPLETED_SUCCESS = 'COMPLETED_SUCCESS';
export const COMPLETED_ERROR = 'COMPLETED_ERROR';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
