const rules = [
	'1. Make sure that you attempt the exam from a laptop/desktop and have good internet connectivity.',
	'2. Use only Google Chrome as your browser to attempt the exam.',
	'3. The duration of the test is 50 mins and 10 mins extra will be provided at the end for uploading the answer sheet. No extra time will be provided.',
	'4. No change of slots will be entertained (under critical circumstances get in touch with your mentors).',
	'5. No malpractices should be followed while giving the exam. Anyone found doing so will be exempted from the exam.',
	'6. In case, any issues are faced while attempting the exam, the assigned mentor only should be contacted.',
	'7. It’s great to have choices in the life but it is mandatory to attempt the Management and logical reasoning and at least one of the three technical sections provided (CSE, Electrical, Mechanical). You can attempt multiple sections.',
	'8. In Logical Section you will be rewarded +3 marks for a correct answer and - 1 for wrong answer and for all the other domains +3 marks for a correct answer and no negative marks for wrong answer.',
	'9. For MCQs, write down the option as well as the answer [ex: b) python]. ',
	'10. Answers should be written on paper only, scanned (as a pdf) and uploaded with the name of the file in the following format: RegistrationNumber(in uppercase)_Name(in lowercase).',
	'11. It is natural to feel “there are many better than me in the class”. Do not validate by looking in their papers. (DO NOT COPY)',
	'12. You cannot use mobile phone or calculator during examination.',
	'13. Writing a test is about what you know and not what you hope to get out of luck. (Write the answer only when you are sure)',
	'14. Enjoy solving the paper from your heart as if you have met your soul mate. Show all your zeal and enthusiasm to attempt the questions.',
	'15 .If you know nothing don’t be disheartened, even “Jon Snow knows nothing”.',
	'16. It is advised for you to attempt your preferred technical section first. Only after that, attempt the questions from other sections.',
	'17. You can use the language of your preferance for CSE coding questions',
	'18. Do not forget to fill the form before leaving the meeting.',
];
export default rules;
